<a href="https://colab.research.google.com/github/habilg/colab/blob/master/01_Pytorch%2C_tensors1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.12.1+cu113


In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
#torch.set_default_dtype(torch.float64) torch.float16

# Create Tensors



In [5]:
tensor_arr= torch.Tensor([[1,2,3],[4,5,6]]) # is alias for torch.FloatTensor()
numpy_arr=np.array([[1,2,3],[4,5,6]])

In [6]:
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [9]:
torch.numel(tensor_arr)

6

In [10]:
np.size(numpy_arr)

6

In [11]:
tensor_uninitialized= torch.Tensor(2,2)
tensor_uninitialized

tensor([[1.0163e-34, 0.0000e+00],
        [3.3631e-44, 0.0000e+00]])

In [14]:
tensor_initialized=torch.rand(2,2)
tensor_initialized

tensor([[0.2974, 0.6244],
        [0.5497, 0.8500]])

In [16]:
tensor_initialized_normal=torch.randn(2,2)
tensor_initialized_normal

tensor([[ 1.2225,  3.0498],
        [-0.4034,  1.6983]])

In [19]:
array_initialized_normal= np.random.normal(size=(2,2))
array_initialized_normal

array([[-1.65748112, -1.84460055],
       [-1.45167775,  0.57240479]])

In [20]:
tensor_int= torch.tensor([5,3]).type(torch.IntTensor) # create a tensor for CPU
tensor_int

tensor([5, 3], dtype=torch.int32)

In [22]:
tensor_short= torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [24]:
tensor_half_float= torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_half_float

tensor([1., 2., 3.], dtype=torch.float16)

In [25]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [26]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [27]:
torch.full((2,2),fill_value=10)

tensor([[10, 10],
        [10, 10]])

In [29]:
tensor_eye=torch.eye(4)
tensor_eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [30]:
torch.nonzero(tensor_eye)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

### "_like" functions
zeros_like, ones_like

torch.tensor always makes a copy of the underlying data of the tensor

### SPARSE  tensors

In [43]:
i= torch.Tensor([[0,1,1],
                 [2,2,0]])


In [50]:
v=torch.Tensor([3,4,5])

In [51]:
sparse_tensor= torch.sparse_coo_tensor(i,v,[2,5])

In [53]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

# Operations

"_" functions : change the tensor inplace

In [55]:
initial_tensor=torch.rand(4,4)
initial_tensor

tensor([[0.0637, 0.6601, 0.0357, 0.7289],
        [0.1051, 0.0856, 0.1847, 0.8572],
        [0.7711, 0.7745, 0.5348, 0.5640],
        [0.6546, 0.0545, 0.4191, 0.2801]])

In [57]:
initial_tensor.fill_(10) 

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [58]:
initial_tensor

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [59]:
new_tensor= initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15., 15.],
        [15., 15., 15., 15.],
        [15., 15., 15., 15.],
        [15., 15., 15., 15.]])

In [60]:
initial_tensor

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [62]:
new_tensor2=initial_tensor.add_(5)
new_tensor2

tensor([[20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.]])

In [63]:
initial_tensor

tensor([[20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.]])

In [64]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730, 3.8730]])

In [66]:
x= torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [69]:
tensor_chunk=torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [70]:
tensor1= tensor_chunk[0]
tensor2= tensor_chunk[1]
tensor3=torch.Tensor([3,4,5])

torch.cat((tensor1,tensor2,tensor3),0) 

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [74]:
random_tensor=torch.randint(10,(3,3))
random_tensor

tensor([[6, 5, 7],
        [9, 0, 3],
        [9, 6, 8]])

In [76]:
random_tensor.size()

torch.Size([3, 3])

In [77]:
random_tensor[1,0]

tensor(9)

In [80]:
resized_tensor=random_tensor.view(9) #share the same memory with original tensor!
resized_tensor

tensor([6, 5, 7, 9, 0, 3, 9, 6, 8])

In [79]:
random_tensor

tensor([[6, 5, 7],
        [9, 0, 3],
        [9, 6, 8]])

In [81]:
random_tensor[2,2]=100.0
resized_tensor

tensor([  6,   5,   7,   9,   0,   3,   9,   6, 100])

In [82]:
random_tensor.shape

torch.Size([3, 3])

In [83]:
#reshaping 
tensor_unsqueeze= torch.unsqueeze(random_tensor,1)

In [85]:
tensor_unsqueeze.shape

torch.Size([3, 1, 3])

In [86]:
tensor_transpose=torch.transpose(random_tensor,0,1)

In [87]:
tensor_transpose

tensor([[  6,   9,   9],
        [  5,   0,   6],
        [  7,   3, 100]])

In [88]:
sorted_tensor,sorted_indices = torch.sort(random_tensor)

In [89]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [90]:
sorted_tensor

tensor([[  5,   6,   7],
        [  0,   3,   9],
        [  6,   9, 100]])

In [92]:
rand1=torch.abs(torch.randn(2,3))
rand2=torch.abs(torch.randn(2,3))

In [93]:
add1=rand1+rand2
add1

tensor([[1.1308, 0.8266, 0.8464],
        [0.6153, 3.4740, 3.2324]])

In [95]:
add2=torch.add(rand1,rand2)
add2

tensor([[1.1308, 0.8266, 0.8464],
        [0.6153, 3.4740, 3.2324]])

In [96]:
add3= rand2+3

In [97]:
add3

tensor([[3.7199, 3.2167, 3.5440],
        [3.0867, 5.0861, 3.9538]])

In [98]:
tensor= torch.Tensor([[-1,-2,-3],[1,2,3]])
tensor_div=torch.div(tensor, tensor+0.3)

In [99]:
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [101]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [103]:
tensor_clamp= torch.clamp(tensor, min=-0.2 , max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [105]:
t1=torch.Tensor([1,2])
t2=torch.Tensor([10,20])
dot_product= torch.dot(t1,t2)
dot_product

tensor(50.)

In [107]:
matrix= torch.Tensor([[1,2,3],[4,5,6]]) #2*3
vector= torch.Tensor([0,1,2]) #3*1
matrix_vector= torch.mv(matrix,vector) #2*1
matrix_vector

tensor([ 8., 17.])

In [108]:
another_matrix= torch.Tensor([[1,2],[3,4],[5,6]])
matrix_mul = torch.mm(matrix,another_matrix)
matrix_mul

tensor([[22., 28.],
        [49., 64.]])

In [110]:
matrix_mul2= torch.mm(matrix,another_matrix)

In [112]:
matrix_mul2

tensor([[22., 28.],
        [49., 64.]])

In [113]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [114]:
torch.argmin(matrix_mul,dim=1)

tensor([0, 0])

## Numpy and Torch relationship

In [115]:
# tghe NumPy array and the PyTorch tensor share the same underlying memory